In [6]:
import numpy as np
import matplotlib.pyplot as plt
import math

#### Using fft.dct

In [98]:
from scipy import fft
test = fft.dct([1, 2, 3, 4], 2, norm='ortho')

In [99]:
test

array([ 5.        , -2.2304425 ,  0.        , -0.15851267])

#### Build 1D-DCT II Function

In [108]:
def dct(data):
    N = len(data)
    f = 0
    cof = np.zeros(N)
    for k in range(N):
        if k==0:
            f = math.sqrt(1/(4*N))
        else:
            f = math.sqrt(1/(2*N))

        s = 0
        for n in range(N):
            out = data[n] * math.cos((math.pi*k) / (2*N) * (2*n+1))
            s = s + out
        cof[k] = 2 * f * s
    return np.around(cof, decimals=7)

In [74]:
data = np.array([1,2, 3, 4])
data

array([1, 2, 3, 4])

In [112]:
output = dct(data)
output

array([ 5.       , -2.2304425, -0.       , -0.1585127])